SELECT DISTINCT
Emp.Employee_Code,
Emp.Employee_Name, 
Emp.Account,
Emp.BPS,
Emp.Fix,
Desig.Designation,
dept.Department_Name,
Ded.House_Rent_1,
Ded.House_Rent_2,
Ded.Electric_Charges_1,
Ded.Electric_Charges_2,
Ded.SuiGas_Charges,
Ded.Water_Tax1_Charges,
Ded.Water_Tax2_Charges,
Ded.Endovement_Fund,
Ded.B_Fund,
Ded.House_Build_Loan,
Ded.Convence_Loan,
Ded.GP_Fund_Regular,
Ded.GP_Fund_Advence,
Ded.Eid_Advance,
Ded.Union_Fund_1,
Ded.Union_Fund_2,
Ded.Vehicle_Charges_Other,
Ded.Vehicle_Charges_Teacher,
Ded.Upkeep_Ded,
Ded.R_Leave_Without_Pay,
Ded.Recovery_Gap_CA,
Ded.Income_Tax,
Ded.Group_Insurance,
Ded.Other,
Net.totalDeduction,
Net.Net_Salary
FROM Employee Emp, employee_teaching EmpTeach, Designation Desig, deduction Ded, netsalary Net, department Dept
WHERE Emp.Designation_ID=Desig.Designation_ID AND Emp.Employee_Code=Net.Employee_Code AND Emp.Employee_Code=Ded.Employee_Code 
AND Emp.Employee_Code=EmpTeach.Employee_Code AND EmpTeach.Department_ID=Dept.Department_ID